server:
  port: 8083

spring:
  application:
    name: bidding-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/mshando_bidding}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres123}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.mshando.biddingservice: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKey}
  expiration: ${JWT_EXPIRATION:86400000}

# Inter-service communication
services:
  user-service:
    url: ${USER_SERVICE_URL:http://localhost:8081}
  task-service:
    url: ${TASK_SERVICE_URL:http://localhost:8082}

# Business Configuration
bidding:
  auto-accept:
    enabled: ${BID_AUTO_ACCEPT_ENABLED:false}
    threshold-hours: ${BID_AUTO_ACCEPT_THRESHOLD:24}
  max-bids-per-task: ${MAX_BIDS_PER_TASK:10}
  min-bid-amount: ${MIN_BID_AMOUNT:5.00}

---
# Local Development Profile
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/mshando_bidding
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    com.mshando.biddingservice: DEBUG

---
# Test Profile
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

---
# Production Profile
spring:
  config:
    activate:
      on-profile: production
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

logging:
  level:
    com.mshando.biddingservice: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN

---
# Docker Profile
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/taskrabbit_bidding
    username: postgres
    password: postgres123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: bidding-service

services:
  user-service:
    url: http://user-service:8081
  task-service:
    url: http://task-service:8082

logging:
  level:
    com.mshando.biddingservice: INFO
